### ISSUE TITLE
Link the events page to the main page

### ISSUE THREAD

**Issue by Alemkin** [codefortallahassee/code4tally-website#2]
For the event linkup, would you want to change the eventbrite link to point at the events page and rename the link? And just add a return to homepage button on the events page? I can do that if you agree
@bpeterso2000

**Comment by bpeterso2000** [comment]
What do you think? I kind of like how the "EVENTBRITE" button is consistent with the other service buttons like "GITHUB", "TRELLO", etc.  What do you think about moving the events page inline with the main landing page after the "About" section and then adding a menu item called "Events" that links to the section?  Feel free to use your judgement, I'm not totally sold on one way or the other.

**Comment by Alemkin** [comment]
I like that idea

**Comment by Alemkin** [comment]
Fixed with commits: f71ae90c5ae5b3708e151da86a8c1fd70cc14e0d and 2560e39ffc203c1bc3a2ffa92c2ab7e2a12689ed
